services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app  # Mount the current directory into the container
      - ./logs:/app/logs  # Mount the logs directory to persist logs outside the container
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 8g
          cpus: '2.0'
